// Code generated by goyacc -o .\lang.go lang.y. DO NOT EDIT.

//line lang.y:1

package lang

import __yyfmt__ "fmt"

//line lang.y:3

//line lang.y:6
type yySymType struct {
	yys      int
	expr     ExprNode
	exprList []ExprNode
	str      string
	num      float64
	boolean  bool
}

const IDENTIFIER = 57346
const STRING = 57347
const DSTRING = 57348
const NUMBER = 57349
const BOOLEAN = 57350
const AND = 57351
const OR = 57352
const NOT = 57353
const IN = 57354
const EQ = 57355
const NE = 57356
const LT = 57357
const LE = 57358
const GT = 57359
const GE = 57360
const LPAREN = 57361
const RPAREN = 57362
const LBRACKET = 57363
const RBRACKET = 57364
const DOT = 57365
const COMMA = 57366
const QUOTE = 57367
const DQUOTE = 57368
const COLON = 57369
const QMARK = 57370
const UMINUS = 57371

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING",
	"DSTRING",
	"NUMBER",
	"BOOLEAN",
	"AND",
	"OR",
	"NOT",
	"IN",
	"EQ",
	"NE",
	"LT",
	"LE",
	"GT",
	"GE",
	"LPAREN",
	"RPAREN",
	"LBRACKET",
	"RBRACKET",
	"DOT",
	"COMMA",
	"QUOTE",
	"DQUOTE",
	"COLON",
	"QMARK",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"UMINUS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line lang.y:179

func ParseExpression(input string) (ExprNode, error) {
	yyErrorVerbose = true
	lexer := &yyLex{input: input}
	yyParse(lexer)
	if lexer.error != nil {
		return nil, lexer.error
	}
	return lexer.result, nil
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 147

var yyAct = [...]int8{
	65, 2, 6, 63, 34, 35, 32, 33, 12, 14,
	15, 13, 16, 7, 71, 9, 84, 75, 41, 72,
	76, 76, 44, 17, 85, 21, 81, 82, 5, 49,
	50, 51, 52, 53, 10, 12, 14, 15, 13, 16,
	60, 67, 9, 68, 73, 66, 55, 56, 70, 39,
	17, 38, 21, 47, 48, 40, 54, 69, 62, 61,
	59, 10, 1, 74, 12, 14, 15, 13, 16, 77,
	4, 9, 42, 80, 79, 24, 25, 83, 20, 17,
	78, 21, 12, 14, 15, 13, 16, 19, 18, 9,
	10, 22, 23, 45, 46, 8, 11, 17, 64, 21,
	12, 14, 15, 13, 16, 36, 37, 9, 10, 3,
	0, 0, 0, 0, 0, 17, 0, 21, 43, 0,
	12, 14, 15, 13, 16, 0, 10, 9, 0, 0,
	57, 58, 0, 0, 0, 17, 0, 21, 31, 30,
	0, 0, 26, 27, 28, 29, 10,
}

var yyPact = [...]int16{
	116, -1000, -1000, 82, 62, 127, -23, -27, -1000, 116,
	116, 28, 36, -1000, -1000, -1000, -1000, 116, -1000, -1000,
	-1000, 96, 116, 116, 116, 116, 116, 116, 116, 116,
	116, 44, 116, 116, 116, 116, -1000, -1000, 56, 31,
	78, 25, 19, -1000, -1000, 62, 62, 127, 127, -23,
	-23, -23, -23, -23, 116, -27, -27, -1000, -1000, 29,
	-8, 22, 116, -3, -1000, -1000, -1000, -1000, 116, -23,
	60, -1000, 4, -1000, 5, -1000, 116, -1000, -1000, -4,
	2, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 0, 109, 70, 28, 2, 13, 95, 96, 88,
	87, 78, 3, 72, 62,
}

var yyR1 = [...]int8{
	0, 14, 1, 2, 2, 2, 3, 3, 3, 4,
	4, 4, 4, 4, 4, 4, 5, 5, 5, 6,
	6, 6, 7, 7, 7, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 9, 9, 9, 9, 9, 9,
	10, 10, 10, 10, 11, 11, 12, 12, 13, 13,
}

var yyR2 = [...]int8{
	0, 1, 1, 3, 3, 1, 3, 3, 1, 3,
	3, 3, 3, 3, 4, 1, 3, 3, 1, 3,
	3, 1, 2, 2, 1, 1, 1, 1, 1, 1,
	3, 1, 1, 1, 3, 4, 4, 6, 5, 5,
	4, 3, 5, 6, 3, 2, 1, 3, 1, 3,
}

var yyChk = [...]int16{
	-1000, -14, -1, -2, -3, -4, -5, -6, -7, 11,
	30, -8, 4, 7, 5, 6, 8, 19, -9, -10,
	-11, 21, 9, 10, 13, 14, 15, 16, 17, 18,
	12, 11, 29, 30, 31, 32, -7, -7, 23, 21,
	19, -1, -13, 22, -1, -3, -3, -4, -4, -5,
	-5, -5, -5, -5, 12, -6, -6, -7, -7, 4,
	-1, 28, 27, -12, 20, -1, 20, 22, 24, -5,
	19, 22, 27, 22, -1, 20, 24, -1, 20, -12,
	-1, 22, 22, -1, 20, 22,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 5, 8, 15, 18, 21, 0,
	0, 24, 25, 26, 27, 28, 29, 0, 31, 32,
	33, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 22, 23, 0, 0,
	0, 0, 0, 45, 48, 3, 4, 6, 7, 9,
	10, 11, 12, 13, 0, 16, 17, 19, 20, 34,
	0, 0, 0, 0, 41, 46, 30, 44, 0, 14,
	0, 35, 0, 36, 0, 40, 0, 49, 42, 0,
	0, 39, 38, 47, 43, 37,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 31, 29, 3, 30, 3, 32,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 33,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:40
		{
			yylex.(*yyLex).result = yyDollar[1].expr
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:42
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:44
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: "and"}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:47
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: "or"}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:50
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:52
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: "="}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:55
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: "!="}
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:58
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:60
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: "<"}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:63
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: "<="}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:66
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: ">"}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:69
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: ">="}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:72
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: "in"}
		}
	case 14:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lang.y:75
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[4].expr, Operator: "not in"}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:78
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:80
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: "+"}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:83
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: "-"}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:86
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:88
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: "*"}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:91
		{
			yyVAL.expr = &BinaryOpNode{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Operator: "/"}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:94
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lang.y:96
		{
			yyVAL.expr = &UnaryOpNode{Operand: yyDollar[2].expr, Operator: "not"}
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lang.y:99
		{
			yyVAL.expr = &UnaryOpNode{Operand: yyDollar[2].expr, Operator: "-"}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:102
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:104
		{
			yyVAL.expr = &VariableNode{Name: yyDollar[1].str}
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:107
		{
			yyVAL.expr = &LiteralNode{Value: NumberValue(yyDollar[1].num)}
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:110
		{
			yyVAL.expr = &LiteralNode{Value: StringValue(yyDollar[1].str)}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:113
		{
			yyVAL.expr = &LiteralNode{Value: StringValue(yyDollar[1].str)}
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:116
		{
			yyVAL.expr = &LiteralNode{Value: BoolValue(yyDollar[1].boolean)}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:119
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:122
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:123
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:124
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:126
		{
			yyVAL.expr = &FieldAccessNode{Object: yyDollar[1].expr, Field: yyDollar[3].str}
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lang.y:129
		{
			yyVAL.expr = &IndexAccessNode{Object: yyDollar[1].expr, Index: yyDollar[3].expr}
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lang.y:132
		{
			yyVAL.expr = &IndexAccessNode{Object: yyDollar[1].expr, Index: &EachNode{}}
		}
	case 37:
		yyDollar = yyS[yypt-6 : yypt+1]
//line lang.y:135
		{
			yyVAL.expr = &IndexAccessNode{Object: yyDollar[1].expr, Index: &RangeNode{Begin: yyDollar[3].expr, End: yyDollar[5].expr}}
		}
	case 38:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lang.y:138
		{
			yyVAL.expr = &IndexAccessNode{Object: yyDollar[1].expr, Index: &RangeNode{Begin: NumberValue(0), End: yyDollar[4].expr}}
		}
	case 39:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lang.y:141
		{
			yyVAL.expr = &IndexAccessNode{Object: yyDollar[1].expr, Index: &RangeNode{Begin: yyDollar[3].expr, End: NumberValue(-1)}}
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lang.y:145
		{
			yyVAL.expr = &FunctionCallNode{Name: yyDollar[1].str, Args: yyDollar[3].exprList}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:148
		{
			yyVAL.expr = &FunctionCallNode{Name: yyDollar[1].str, Args: []ExprNode{}}
		}
	case 42:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lang.y:151
		{
			yyVAL.expr = &FunctionCallNode{Namespace: yyDollar[1].expr, Name: yyDollar[3].str, Args: []ExprNode{}}
		}
	case 43:
		yyDollar = yyS[yypt-6 : yypt+1]
//line lang.y:154
		{
			yyVAL.expr = &FunctionCallNode{Namespace: yyDollar[1].expr, Name: yyDollar[3].str, Args: yyDollar[5].exprList}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:158
		{
			yyVAL.expr = &ListNode{Elements: yyDollar[2].exprList}
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lang.y:161
		{
			yyVAL.expr = &ListNode{Elements: []ExprNode{}}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:165
		{
			yyVAL.exprList = []ExprNode{yyDollar[1].expr}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:168
		{
			yyVAL.exprList = append(yyDollar[1].exprList, yyDollar[3].expr)
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lang.y:172
		{
			yyVAL.exprList = []ExprNode{yyDollar[1].expr}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lang.y:175
		{
			yyVAL.exprList = append(yyDollar[1].exprList, yyDollar[3].expr)
		}
	}
	goto yystack /* stack new state and value */
}
